apiVersion: v1
kind: Service
metadata:
  name: {{ include "express-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "express-webapp.name" . }}
    helm.sh/chart: {{ include "express-webapp.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "express-webapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
